const districts = [
  {
    id: 100,
    name: 'Attock',
    mapKey: 'pk-pb-atk',
    province: 'Attock',
  },
  {
    id: 200,
    name: 'Bahawal Nagar',
    mapKey: 'pk-pb-bng',
    province: 'Bahawal-Nagar',
  },
  {
    id: 300,
    name: 'Bahawalpur',
    mapKey: 'pk-pb-bwp',
    province: 'Bahawalpur',
  },
  {
    id: 400,
    name: 'Bhakkar',
    mapKey: 'pk-pb-bkr',
    province: 'Bhakkar',
  },
  {
    id: 500,
    name: 'Chakwal',
    mapKey: 'pk-pb-ckw',
    province: 'Chakwal',
  },
  {
    id: 600,
    name: 'Chiniot',
    mapKey: 'pk-pb-chn',
    province: 'Chiniot',
  },
  {
    id: 700,
    name: 'Dera Ghazi Khan',
    mapKey: 'pk-pb-dgk',
    province: 'Dera-Ghazi-Khan',
  },
  {
    id: 800,
    name: 'Faisalabad',
    mapKey: 'pk-pb-fsd',
    province: 'Faisalabad',
  },
  {
    id: 900,
    name: 'Gujranwala',
    mapKey: 'pk-pb-gwl',
    province: 'Gujranwala',
  },
  {
    id: 1000,
    name: 'Gujrat',
    mapKey: 'pk-pb-guj',
    province: 'Gujrat',
  },
  {
    id: 1100,
    name: 'Hafizabad',
    mapKey: 'pk-pb-hfz',
    province: 'Hafizabad',
  },
  { id: 1200, name: 'Jhang', mapKey: 'pk-pb-jhn', province: 'Jhang' },
  {
    id: 1300,
    name: 'Jhelum',
    mapKey: 'pk-pb-jhl',
    province: 'Jhelum',
  },
  { id: 1400, name: 'Kasur', mapKey: 'pk-pb-ksr', province: 'Kasur' },
  {
    id: 1500,
    name: 'Khanewal',
    mapKey: 'pk-pb-kwl',
    province: 'Khanewal',
  },
  {
    id: 1600,
    name: 'Khushab',
    mapKey: 'pk-pb-ksb',
    province: 'Khushab',
  },
  {
    id: 1700,
    name: 'Lahore',
    mapKey: 'pk-pb-lhr',
    province: 'Lahore',
  },
  {
    id: 1800,
    name: 'Layyah',
    mapKey: 'pk-pb-lyh',
    province: 'Layyah',
  },
  {
    id: 1900,
    name: 'Lodhran',
    mapKey: 'pk-pb-ldr',
    province: 'Lodhran',
  },
  {
    id: 2000,
    name: 'Mandi Bahauddin',
    mapKey: 'pk-pb-mbh',
    province: 'Mandi-Bahauddin',
  },
  {
    id: 2100,
    name: 'Mianwali',
    mapKey: 'pk-pb-mwl',
    province: 'Mianwali',
  },
  {
    id: 2200,
    name: 'Multan',
    mapKey: 'pk-pb-mtn',
    province: 'Multan',
  },
  {
    id: 2300,
    name: 'Muzaffargarh',
    mapKey: 'pk-pb-mzg',
    province: 'Muzaffargarh',
  },
  {
    id: 2400,
    name: 'Nankana Sahib',
    mapKey: 'pk-pb-nsb',
    province: 'Nankana-Sahib',
  },
  {
    id: 2500,
    name: 'Narowal',
    mapKey: 'pk-pb-nrw',
    province: 'Narowal',
  },
  { id: 2600, name: 'Okara', mapKey: 'pk-pb-okr', province: 'Okara' },
  {
    id: 2700,
    name: 'Pakpattan',
    mapKey: 'pk-pb-ptn',
    province: 'Pakpattan',
  },
  {
    id: 2800,
    name: 'Rahimyar Khan',
    mapKey: 'pk-pb-ryk',
    province: 'Rahimyar-Khan',
  },
  {
    id: 2900,
    name: 'Rajanpur',
    mapKey: 'pk-pb-rjp',
    province: 'Rajanpur',
  },
  {
    id: 3000,
    name: 'Rawalpindi',
    mapKey: 'pk-pb-rwp',
    province: 'Rawalpindi',
  },
  {
    id: 3100,
    name: 'Sahiwal',
    mapKey: 'pk-pb-shw',
    province: 'Sahiwal',
  },
  {
    id: 3200,
    name: 'Sargodha',
    mapKey: 'pk-pb-sgh',
    province: 'Sargodha',
  },
  {
    id: 3300,
    name: 'Sheikhupura',
    mapKey: 'pk-pb-skp',
    province: 'Sheikhupura',
  },
  {
    id: 3400,
    name: 'Sialkot',
    mapKey: 'pk-pb-slk',
    province: 'Sialkot',
  },
  {
    id: 3500,
    name: 'Toba Tek Singh',
    mapKey: 'pk-pb-tts',
    province: 'Toba-Tek-Singh',
  },
  {
    id: 3600,
    name: 'Vehari',
    mapKey: 'pk-pb-veh',
    province: 'Vehari',
  },
  {
    id: 10100,
    name: 'Abbottabad',
    mapKey: 'pk-nw-abt',
    province: 'Abbottabad',
  },
  {
    id: 10200,
    name: 'Bannu',
    mapKey: 'pk-nw-ban',
    province: 'Bannu',
  },
  {
    id: 10300,
    name: 'Batagram',
    mapKey: 'pk-nw-btm',
    province: 'Batagram',
  },
  {
    id: 10400,
    name: 'Buner',
    mapKey: 'pk-nw-bun',
    province: 'Buner',
  },
  {
    id: 10500,
    name: 'Charsadda',
    mapKey: 'pk-nw-csd',
    province: 'Charsadda',
  },
  {
    id: 10600,
    name: 'Lower Chitral',
    mapKey: 'pk-nw-ctl',
    province: 'Lower-Chitral',
  },
  {
    id: 10700,
    name: 'Dera Ismail Khan',
    mapKey: 'pk-nw-dik',
    province: 'Dera-Ismail-Khan',
  },
  {
    id: 10800,
    name: 'Hangu',
    mapKey: 'pk-nw-hng',
    province: 'Hangu',
  },
  {
    id: 10900,
    name: 'Haripur',
    mapKey: 'pk-nw-hrp',
    province: 'Haripur',
  },
  {
    id: 11000,
    name: 'Karak',
    mapKey: 'pk-nw-krk',
    province: 'Karak',
  },
  {
    id: 11100,
    name: 'Kohat',
    mapKey: 'pk-nw-kht',
    province: 'Kohat',
  },
  {
    id: 11200,
    name: 'Kohistan',
    mapKey: 'pk-nw-kst',
    province: 'Kohistan',
  },
  {
    id: 11300,
    name: 'Lakki Marwat',
    mapKey: 'pk-nw-lmt',
    province: 'Lakki-Marwat',
  },
  {
    id: 11400,
    name: 'Lower Dir',
    mapKey: 'pk-nw-ldr',
    province: 'Lower-Dir',
  },
  {
    id: 11500,
    name: 'Malakand',
    mapKey: 'pk-nw-mkd',
    province: 'Malakand',
  },
  {
    id: 11600,
    name: 'Mansehra',
    mapKey: 'pk-nw-mns',
    province: 'Mansehra',
  },
  {
    id: 11700,
    name: 'Mardan',
    mapKey: 'pk-nw-mrd',
    province: 'Mardan',
  },
  {
    id: 11800,
    name: 'Nowshera',
    mapKey: 'pk-nw-now',
    province: 'Nowshera',
  },
  {
    id: 11900,
    name: 'Peshawar',
    mapKey: 'pk-nw-psh',
    province: 'Peshawar',
  },
  {
    id: 12000,
    name: 'Shangla',
    mapKey: 'pk-nw-sng',
    province: 'Shangla',
  },
  {
    id: 12100,
    name: 'Swabi',
    mapKey: 'pk-nw-swb',
    province: 'Swabi',
  },
  { id: 12200, name: 'Swat', mapKey: 'pk-nw-swt', province: 'Swat' },
  { id: 12300, name: 'Tank', mapKey: 'pk-nw-tnk', province: 'Tank' },
  {
    id: 12400,
    name: 'Torghar',
    mapKey: 'pk-nw-tgr',
    province: 'Torghar',
  },
  {
    id: 12500,
    name: 'Upper Dir',
    mapKey: 'pk-nw-udr',
    province: 'Upper-Dir',
  },
  {
    id: 12600,
    name: 'Upper Chitral',
    mapKey: 'pk-kp-ctl',
    province: 'Upper-Chitral',
  },
  {
    id: 12700,
    name: 'Sari Naurang',
    mapKey: 'pk-kp-sng',
    province: 'Sari-Naurang',
  },
  { id: 12800, name: 'Kurram', mapKey: '', province: 'Kurram' },
  { id: 12900, name: 'Mohmand', mapKey: '', province: 'Mohmand' },
  { id: 13000, name: 'Orakzai', mapKey: '', province: 'Orakzai' },
  {
    id: 13100,
    name: 'S.Waziristan',
    mapKey: '',
    province: 'S.Waziristan',
  },
  {
    id: 20100,
    name: 'Badin',
    mapKey: 'pk-sd-bdn',
    province: 'Badin',
  },
  { id: 20200, name: 'Dadu', mapKey: 'pk-sd-dad', province: 'Dadu' },
  {
    id: 20300,
    name: 'Ghotki',
    mapKey: 'pk-sd-gtk',
    province: 'Ghotki',
  },
  {
    id: 20400,
    name: 'Hyderabad',
    mapKey: 'pk-sd-hyd',
    province: 'Hyderabad',
  },
  {
    id: 20500,
    name: 'Jacobabad',
    mapKey: 'pk-sd-jac',
    province: 'Jacobabad',
  },
  {
    id: 20600,
    name: 'Jamshoro',
    mapKey: 'pk-sd-jsr',
    province: 'Jamshoro',
  },
  {
    id: 20700,
    name: 'Kashmore Khandhkot',
    mapKey: 'pk-sd-ksm',
    province: 'Kashmore-Khandhkot',
  },
  {
    id: 20800,
    name: 'Khairpur',
    mapKey: 'pk-sd-krp',
    province: 'Khairpur',
  },
  {
    id: 20900,
    name: 'Larkana',
    mapKey: 'pk-sd-lkn',
    province: 'Larkana',
  },
  {
    id: 21000,
    name: 'Matiari',
    mapKey: 'pk-sd-mtr',
    province: 'Matiari',
  },
  {
    id: 21100,
    name: 'Mirpur Khas',
    mapKey: 'pk-sd-mkh',
    province: 'Mirpur-Khas',
  },
  {
    id: 21200,
    name: 'Naushehro Feroze',
    mapKey: 'pk-sd-nfr',
    province: 'Naushehro-Feroze',
  },
  {
    id: 21300,
    name: 'Sanghar',
    mapKey: 'pk-sd-sng',
    province: 'Sanghar',
  },
  {
    id: 21400,
    name: 'Kamber Shahdadkot',
    mapKey: 'pk-sd-qsk',
    province: 'Kamber-Shahdadkot',
  },
  {
    id: 21500,
    name: 'Shaheed Benazirabad',
    mapKey: 'pk-sd-sba',
    province: 'Shaheed-Benazirabad',
  },
  {
    id: 21600,
    name: 'Shikarpur',
    mapKey: 'pk-sd-skp',
    province: 'Shikarpur',
  },
  {
    id: 21700,
    name: 'Sukkur',
    mapKey: 'pk-sd-suk',
    province: 'Sukkur',
  },
  {
    id: 21800,
    name: 'Tando Allahyar',
    mapKey: 'pk-sd-tay',
    province: 'Tando-Allahyar',
  },
  {
    id: 21900,
    name: 'Thatta',
    mapKey: 'pk-sd-tht',
    province: 'Thatta',
  },
  {
    id: 22000,
    name: 'Tando Muhammad Khan',
    mapKey: 'pk-sd-tmk',
    province: 'Tando-Muhammad-Khan',
  },
  {
    id: 22100,
    name: 'Tharparkar',
    mapKey: 'pk-sd-tpr',
    province: 'Tharparkar',
  },
  {
    id: 22200,
    name: 'Umerkot',
    mapKey: 'pk-sd-ukt',
    province: 'Umerkot',
  },
  {
    id: 22300,
    name: 'Sujawal',
    mapKey: 'pk-sd-suj',
    province: 'Sujawal',
  },
  {
    id: 22400,
    name: 'Karachi',
    mapKey: 'pk-sd-khi',
    province: 'Karachi',
  },
  {
    id: 30100,
    name: 'Awaran',
    mapKey: 'pk-ba-awn',
    province: 'Awaran',
  },
  {
    id: 30200,
    name: 'Barkhan',
    mapKey: 'pk-ba-bkn',
    province: 'Barkhan',
  },
  {
    id: 30300,
    name: 'Chagai',
    mapKey: 'pk-ba-cgh',
    province: 'Chagai',
  },
  {
    id: 30400,
    name: 'Dera Bugti',
    mapKey: 'pk-ba-dbt',
    province: 'Dera-Bugti',
  },
  {
    id: 30500,
    name: 'Gwadar',
    mapKey: 'pk-ba-gwd',
    province: 'Gwadar',
  },
  {
    id: 30600,
    name: 'Harnai',
    mapKey: 'pk-ba-hrn',
    province: 'Harnai',
  },
  {
    id: 30700,
    name: 'Jaffarabad',
    mapKey: 'pk-ba-jaf',
    province: 'Jaffarabad',
  },
  {
    id: 30800,
    name: 'Jhal Magsi',
    mapKey: 'pk-ba-jmg',
    province: 'Jhal-Magsi',
  },
  {
    id: 30900,
    name: 'Kachhi (Bolan)',
    mapKey: 'pk-ba-kai',
    province: 'Kachhi-Bolan',
  },
  {
    id: 31000,
    name: 'Kalat',
    mapKey: 'pk-ba-kal',
    province: 'Kalat',
  },
  { id: 31100, name: 'Kech', mapKey: 'pk-ba-kch', province: 'Kech' },
  {
    id: 31200,
    name: 'Washuk',
    mapKey: 'pk-ba-wsk',
    province: 'Washuk',
  },
  {
    id: 31300,
    name: 'Kharan',
    mapKey: 'pk-ba-khn',
    province: 'Kharan',
  },
  {
    id: 31400,
    name: 'Khuzdar',
    mapKey: 'pk-ba-kzr',
    province: 'Khuzdar',
  },
  {
    id: 31500,
    name: 'Killa Abdullah',
    mapKey: 'pk-ba-kab',
    province: 'Killa-Abdullah',
  },
  {
    id: 31600,
    name: 'Killa Saifullah',
    mapKey: 'pk-ba-ksf',
    province: 'Killa-Saifullah',
  },
  {
    id: 31700,
    name: 'Kohlu',
    mapKey: 'pk-ba-khl',
    province: 'Kohlu',
  },
  {
    id: 31800,
    name: 'Lasbela',
    mapKey: 'pk-ba-lsb',
    province: 'Lasbela',
  },
  {
    id: 31900,
    name: 'Loralai',
    mapKey: 'pk-ba-lrl',
    province: 'Loralai',
  },
  {
    id: 32000,
    name: 'Mastung',
    mapKey: 'pk-ba-mst',
    province: 'Mastung',
  },
  {
    id: 32100,
    name: 'Musakhail',
    mapKey: 'pk-ba-msk',
    province: 'Musakhail',
  },
  {
    id: 32200,
    name: 'Nasirabad',
    mapKey: 'pk-ba-nsr',
    province: 'Nasirabad',
  },
  {
    id: 32300,
    name: 'Nushki',
    mapKey: 'pk-ba-nsk',
    province: 'Nushki',
  },
  {
    id: 32400,
    name: 'Panjgur',
    mapKey: 'pk-ba-png',
    province: 'Panjgur',
  },
  {
    id: 32500,
    name: 'Pishin',
    mapKey: 'pk-ba-pis',
    province: 'Pishin',
  },
  {
    id: 32600,
    name: 'Quetta',
    mapKey: 'pk-ba-qta',
    province: 'Quetta',
  },
  {
    id: 32700,
    name: 'Sherani',
    mapKey: 'pk-ba-srn',
    province: 'Sherani',
  },
  { id: 32800, name: 'Sibi', mapKey: 'pk-ba-sib', province: 'Sibi' },
  {
    id: 32900,
    name: 'Sohbatpur',
    mapKey: 'pk-ba-str',
    province: 'Sohbatpur',
  },
  { id: 33000, name: 'Zhob', mapKey: 'pk-ba-zhb', province: 'Zhob' },
  {
    id: 33100,
    name: 'Ziarat',
    mapKey: 'pk-ba-zrt',
    province: 'Ziarat',
  },
  { id: 33200, name: 'Sohrab', mapKey: 'sohrab', province: 'Sohrab' },
  {
    id: 40100,
    name: 'Islamabad',
    mapKey: 'pk-is-isd',
    province: 'Islamabad',
  },
  { id: 50100, name: 'N.M.D', mapKey: 'pk-ta-ta', province: 'NMD' },
  {
    id: 60100,
    name: 'Azad Kashmir',
    mapKey: 'pk-jk-jk',
    province: 'Azad-Kashmir',
  },
  {
    id: 70100,
    name: 'Gilgit-Baltistan',
    mapKey: 'pk-na-na',
    province: 'Gilgit-Baltistan',
  },
  {
    id: 80100,
    name: 'Jammu & Kashmir',
    mapKey: 'pk-dis-dis',
    province: 'Jammu-Kashmir',
  },
];

const compare = (a, b) => {
  if (a.name < b.name) {
    return -1;
  }
  if (a.name > b.name) {
    return 1;
  }

  return 0;
};

export const generateDistrictOptions = () => {
  districts.sort(compare);

  return districts.map((district) => ({
    metadatas: {
      intlLabel: {
        id: 'Auth.form.district.label',
        defaultMessage: district.name,
      },
    },
    key: district.id,
    value: district.id,
  }));
};
